resource_group = "prod"
location = "central us"
network_interface_name = "nic"
windows_vm_name        = "windows"
adminusername = "azure"
storage_1 = "sa1817"
pubip = "Dynamic"
environment = "prod"